[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (default for Vite)
  publish = "dist"

[build.environment]
  # Node version
  NODE_VERSION = "18"

# SPA redirect rule - ensures client-side routing works
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# MIME types for 3D model files
[[headers]]
  for = "/*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"

[[headers]]
  for = "/*.gltf"
  [headers.values]
    Content-Type = "model/gltf+json" 